name: Publish Release

on:
  release:
    types: [published]

jobs:
  
  github-release:
    name: Upload Packages to pypi
    runs-on: ubuntu-latest
    permissions:
      id-token: write  # IMPORTANT: mandatory for sigstore
    environment:
      name: pypi
      url: https://pypi.org/p/kc3zvd-iot-state
    steps:
      - name: Download all the dists
        uses: robinraju/release-downloader@v1
        with:
          out-file-path: dist/
          extract: true
          releaseId: ${{ github.event.release.id }}
      - name: DEBUG - Check downloaded files
        run: ls -R
      - name: Publish distribution 📦 to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        